// Copyright 2019 Manna Harbour
// https://github.com/manna-harbour/miryoku
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#include "miryoku_layer_alternatives.h"

#if defined (MIRYOKU_ALPHAS_COLEMAKDH)
  #define MIRYOKU_LAYER_BASE MIRYOKU_ALTERNATIVES_BASE_COLEMAKDH
#elif defined (MIRYOKU_ALPHAS_QWERTY)
  #define MIRYOKU_LAYER_BASE MIRYOKU_ALTERNATIVES_BASE_QWERTY
#elif defined (MIRYOKU_ALPHAS_COLEMAK)
  #define MIRYOKU_LAYER_BASE MIRYOKU_ALTERNATIVES_BASE_COLEMAK
#elif defined (MIRYOKU_ALPHAS_DVORAK)
  #define MIRYOKU_LAYER_BASE MIRYOKU_ALTERNATIVES_BASE_DVORAK
#else
  #define MIRYOKU_LAYER_BASE MIRYOKU_ALTERNATIVES_BASE_COLEMAKDH
#endif

#if defined (MIRYOKU_EXTRA_QWERTY)
  #define MIRYOKU_LAYER_EXTRA MIRYOKU_ALTERNATIVES_BASE_QWERTY
#else
  #define MIRYOKU_LAYER_EXTRA MIRYOKU_ALTERNATIVES_BASE_QWERTY
#endif

#if defined (MIRYOKU_TAP_COLEMAKDH)
  #define MIRYOKU_LAYER_TAP MIRYOKU_ALTERNATIVES_TAP_COLEMAKDH
#elif defined (MIRYOKU_TAP_QWERTY)
  #define MIRYOKU_LAYER_TAP MIRYOKU_ALTERNATIVES_TAP_QWERTY
#else
  #define MIRYOKU_LAYER_TAP MIRYOKU_ALTERNATIVES_TAP_COLEMAKDH
#endif

#if defined (MIRYOKU_NAV_INVERTEDT)
  #define MIRYOKU_LAYER_NAV MIRYOKU_ALTERNATIVES_NAV_INVERTEDT
#else
  #define MIRYOKU_LAYER_NAV MIRYOKU_ALTERNATIVES_NAV
#endif

#define MIRYOKU_LAYER_BUTTON MIRYOKU_ALTERNATIVES_BUTTON
#define MIRYOKU_LAYER_MOUSE MIRYOKU_ALTERNATIVES_MOUSE
#define MIRYOKU_LAYER_MEDIA MIRYOKU_ALTERNATIVES_MEDIA
#define MIRYOKU_LAYER_NUM MIRYOKU_ALTERNATIVES_NUM
#define MIRYOKU_LAYER_SYM MIRYOKU_ALTERNATIVES_SYM
#define MIRYOKU_LAYER_FUN MIRYOKU_ALTERNATIVES_FUN
